name: ci

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'vitest.config.ts'

  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'vitest.config.ts'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.28.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint
      - name: Run compile and build packages
        run: pnpm build
      - name: Run tests and collect coverage
        run: pnpm test:c
      - name: Upload coverage reports
        uses: codecov/codecov-action@v2
